from enum import Enum


class ChargingStatus(Enum):
    BOOKED = 'BOOKED'
    REBOOKED = 'REBOOKED'
    STARTED = 'STARTED'
    START_FAILED = "START_FAILED"
    IN_PROGRESS = 'IN_PROGRESS'
    PROGRESS_UPDATE_UNKNOWN = 'PROGRESS_UPDATE_UNKNOWN'
    USER_STOPPED = 'USER_STOPPED'
    COMPLETED = 'COMPLETED'
    TERMINATED = 'TERMINATED'
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
    STOP_FAILED = 'STOP_FAILED'

